services:

  backend:
    build: ./backend
    ports:
      - "${PROD_BACKEND_PORT:-${BACKEND_PORT:-8001}}:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - NEXT_PUBLIC_API_URL=${PROD_NEXT_PUBLIC_API_URL:-${NEXT_PUBLIC_API_URL:-http://localhost:8001}}
      - NODE_ENV=${NODE_ENV:-production}
      - API_URL=${PROD_API_URL:-${API_URL:-http://backend:8000}}
    depends_on:
      - backend
    ports:
      - "${PROD_FRONTEND_PORT:-${FRONTEND_PORT:-3001}}:3000"
    networks:
      - app-network

volumes:
  tiles-data:

networks:
  app-network:
    driver: bridge